const $=selector=>document.querySelector(selector);
const API_BASE=localStorage.getItem('farma_api')||(['localhost','127.0.0.1'].includes(location.hostname)?'http://localhost:8000':'');
const COMMUNES={'Tarapaca':['Iquique'],'Arica y Parinacota':['Arica'],'Antofagasta':['Antofagasta']};
const money=value=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value||0);
const normalize=(value='')=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9%]+/g,' ').trim();
let catalog=[];let offers=[];
async function loadCatalog(){const manifest=await fetch('./data/manifest.json').then(r=>r.json());const region=$('#history-region').value,commune=$('#history-commune').value;const entry=manifest.locations[`${region}|${commune}`];if(!entry)throw new Error('No hay catálogo para esta ubicación');catalog=await fetch(`./data/${entry.file}`).then(r=>r.json());refreshSuggestions('');}
function refreshSuggestions(query){const terms=normalize(query).split(' ').filter(term=>term.length>1);const names=[...new Set(catalog.filter(p=>!terms.length||terms.every(term=>normalize(`${p.name} ${p.brand||''} ${p.active_ingredient||''}`).includes(term))).map(p=>p.name))].slice(0,50);const list=$('#history-products');list.innerHTML='';names.forEach(name=>{const option=document.createElement('option');option.value=name;list.appendChild(option)});}
function updateCommunes(){const select=$('#history-commune');select.innerHTML='';(COMMUNES[$('#history-region').value]||[]).forEach(value=>select.add(new Option(value,value)));return loadCatalog();}
function findOffers(query){const terms=normalize(query).split(' ').filter(term=>term.length>1);return catalog.filter(p=>terms.every(term=>normalize(`${p.name} ${p.brand||''} ${p.active_ingredient||''}`).includes(term))).sort((a,b)=>Number(b.available)-Number(a.available)||a.price-b.price).slice(0,60);}
async function getPoints(offer){if(API_BASE){try{const url=`${API_BASE}/api/history/${encodeURIComponent(offer.pharmacy)}/${encodeURIComponent(offer.sku)}?region=${encodeURIComponent($('#history-region').value)}&commune=${encodeURIComponent($('#history-commune').value)}`;const data=await fetch(url).then(r=>{if(!r.ok)throw new Error();return r.json()});if(data.points?.length)return data.points}catch{}}
return [{price:offer.price,captured_at:offer.captured_at||new Date().toISOString()}];}
function draw(points){const svg=$('#price-chart'),width=760,height=320,pad={x:58,y:42};const prices=points.map(p=>Number(p.price));let min=Math.min(...prices),max=Math.max(...prices);if(min===max){min*=.92;max*=1.08}const x=i=>points.length===1?width/2:pad.x+i*(width-pad.x*2)/(points.length-1);const y=value=>height-pad.y-(value-min)*(height-pad.y*2)/(max-min);const coords=points.map((p,i)=>`${x(i)},${y(Number(p.price))}`).join(' ');const area=points.length>1?`${pad.x},${height-pad.y} ${coords} ${width-pad.x},${height-pad.y}`:'';const grid=[0,.5,1].map(r=>{const yy=pad.y+r*(height-pad.y*2),value=max-r*(max-min);return `<line class="chart-axis" x1="${pad.x}" y1="${yy}" x2="${width-pad.x}" y2="${yy}"/><text x="8" y="${yy+4}" fill="#466b77" font-size="11">${money(value)}</text>`}).join('');const dots=points.map((p,i)=>`<circle class="chart-dot" cx="${x(i)}" cy="${y(Number(p.price))}" r="6"><title>${money(p.price)} · ${new Date(p.captured_at).toLocaleDateString('es-CL')}</title></circle>`).join('');const firstDate=new Date(points[0].captured_at).toLocaleDateString('es-CL'),lastDate=new Date(points.at(-1).captured_at).toLocaleDateString('es-CL');const dates=points.length===1?`<text x="${width/2}" y="${height-10}" text-anchor="middle" fill="#466b77" font-size="11">${firstDate}</text>`:`<text x="${pad.x}" y="${height-10}" fill="#466b77" font-size="11">${firstDate}</text><text x="${width-pad.x}" y="${height-10}" text-anchor="end" fill="#466b77" font-size="11">${lastDate}</text>`;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.innerHTML=`<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#13A797" stop-opacity=".28"/><stop offset="1" stop-color="#13A797" stop-opacity=".02"/></linearGradient></defs>${grid}${area?`<polygon class="chart-area" points="${area}"/>`:''}${points.length>1?`<polyline class="chart-line" points="${coords}"/>`:''}${dots}${dates}`;}
async function renderOffer(index){const offer=offers[index],points=(await getPoints(offer)).sort((a,b)=>String(a.captured_at).localeCompare(String(b.captured_at)));draw(points);const prices=points.map(p=>Number(p.price)),first=prices[0],last=prices.at(-1),change=first?Math.round((last-first)*100/first):0;$('#history-title').textContent=`${offer.name} · ${offer.pharmacy}`;$('#history-current').textContent=money(last);$('#history-min').textContent=money(Math.min(...prices));$('#history-max').textContent=money(Math.max(...prices));$('#history-change').textContent=`${change>0?'+':''}${change}%`;$('#history-count').textContent=points.length;$('#history-note').textContent=points.length<2?'Sólo existe una captura para esta oferta. El gráfico incorporará tendencias después de guardar nuevas actualizaciones del catálogo.':'Variación calculada entre la primera y la última captura disponible.';}
$('#history-form').addEventListener('submit',async event=>{event.preventDefault();offers=findOffers($('#history-query').value);if(!offers.length){$('#history-content').hidden=true;$('#history-status').hidden=false;$('#history-status').textContent='No encontramos productos que coincidan con la consulta.';return}const select=$('#history-offer');select.innerHTML='';offers.forEach((offer,index)=>select.add(new Option(`${offer.pharmacy} · ${offer.name} · ${money(offer.price)}`,index)));$('#history-status').hidden=true;$('#history-content').hidden=false;await renderOffer(0)});
$('#history-offer').addEventListener('change',event=>renderOffer(Number(event.target.value)));$('#history-region').addEventListener('change',updateCommunes);$('#history-commune').addEventListener('change',loadCatalog);$('.menu-btn').addEventListener('click',()=>$('.nav-links').classList.toggle('open'));updateCommunes().catch(()=>{$('#history-status').textContent='No fue posible cargar el catálogo.'});
$('#history-query').addEventListener('input',event=>refreshSuggestions(event.target.value));
