const $=s=>document.querySelector(s),COMMUNES={Tarapaca:['Iquique'],'Arica y Parinacota':['Arica'],Antofagasta:['Antofagasta']};let catalog=[],queries=[];const norm=(v='')=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9%]+/g,' ').trim(),esc=(v='')=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0);const META=/\b(nombre|apellido|edad|direccion|avenida|calle|clinica|telefono|medico|medica|doctor|doctora|diagnostico|rut|firma|fecha|paciente|dosis|tomar|cada|horas?|dias?)\b/i;
async function load(){const m=await fetch('./data/manifest.json').then(r=>r.json()),e=m.locations[`${$('#recipe-region').value}|${$('#recipe-commune').value}`];catalog=e?await fetch(`./data/${e.file}`).then(r=>r.json()):[]}
function communes(){const s=$('#recipe-commune');s.innerHTML='';(COMMUNES[$('#recipe-region').value]||[]).forEach(v=>s.add(new Option(v,v)));load()}
function clean(v){v=v.replace(/^\s*(?:rp\/?\s*)?(?:\d+\s*[.)-]?\s*)?/i,'').replace(/\s+/g,' ').trim();const d=v.match(/\b(\d{1,3}(?:[.\s]\d{3})+|\d+(?:[.,]\d+)?)\s*(mg|mcg|ug|g|ml|ui|iu|u|%)\b/i);if(!d)return v.replace(/^[•*-]+\s*/,'').trim();let name=v.slice(0,d.index).replace(/(?:\(\s*\d+\s*\)|#\s*\d+)\s*$/,'').replace(/[^A-Za-zÁÉÍÓÚÑáéíóúñ -]+$/g,'').trim(),number=d[1];if(/^\d{1,3}(?:[.\s]\d{3})+$/.test(number))number=number.replace(/[.\s]/g,'');const unit=['iu','u'].includes(d[2].toLowerCase())?'UI':d[2];return `${name} ${number} ${unit}`}
function matches(q){const terms=norm(q).split(' ').filter(t=>t.length>1&&!/^\d+$/.test(t));return catalog.filter(p=>p.price>0&&terms.every(t=>norm(`${p.name} ${p.brand||''} ${p.active_ingredient||''}`).includes(t)))}
function candidates(text){const seen=new Set(),out=[];for(const raw of text.split(/\r?\n/)){const q=clean(raw);if(q.length<3||META.test(norm(q)))continue;const key=norm(q);if(seen.has(key))continue;if(matches(q).length||/\d+\s*(?:mg|g|ml|ui|iu|u|%)/i.test(q)){seen.add(key);out.push(q)}}return out.slice(0,20)}
function review(text,items){queries=items;$('#recipe-page-output').innerHTML=`<div class="recipe-review"><b>Revisa los medicamentos antes de comparar</b><label>Un medicamento por línea<textarea id="reviewed" rows="6">${esc(items.join('\n'))}</textarea></label><details><summary>Ver texto completo detectado</summary><pre>${esc(text)}</pre></details></div>${items.length?'':'<div class="recipe-warning">No identificamos medicamentos automáticamente. Revisa el texto detectado y escríbelos manualmente.</div>'}`;$('#reviewed').addEventListener('input',e=>queries=e.target.value.split(/\r?\n/).map(clean).filter(Boolean))}
async function prepare(file){const b=await createImageBitmap(file),scale=Math.min(4,Math.max(2,1600/b.width)),c=document.createElement('canvas');c.width=b.width*scale;c.height=b.height*scale;const x=c.getContext('2d',{willReadFrequently:true});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(b,0,0,c.width,c.height);b.close();const im=x.getImageData(0,0,c.width,c.height);for(let i=0;i<im.data.length;i+=4){const g=.299*im.data[i]+.587*im.data[i+1]+.114*im.data[i+2],v=g>225?255:Math.max(0,Math.min(255,(g-128)*1.55+128));im.data[i]=im.data[i+1]=im.data[i+2]=v}x.putImageData(im,0,0);return c}
async function process(file){const o=$('#recipe-page-output');if(!file)return;if(file.size>10*1024*1024){o.textContent='El archivo supera 10 MB.';return}o.innerHTML='<div class="ocr-progress"><b>Procesando receta…</b><span>Preparando lectura</span><i style="--progress:5%"></i></div>';if(!window.Tesseract){o.textContent='No se pudo cargar el lector OCR.';return}try{const image=await prepare(file),r=await Tesseract.recognize(image,'spa',{tessedit_pageseg_mode:'6',logger:m=>{if(m.status==='recognizing text'){const s=o.querySelector('span'),i=o.querySelector('i');if(s)s.textContent=`Reconociendo texto… ${Math.round(m.progress*100)}%`;if(i)i.style.setProperty('--progress',`${m.progress*100}%`)}}}),text=r.data?.text||'';review(text,candidates(text))}catch(e){o.innerHTML=`<div class="recipe-warning">No pudimos leer la imagen. ${esc(e.message||'')}</div>`}}
$('#recipe-file-page').addEventListener('change',e=>process(e.target.files[0]));const zone=$('#recipe-drop-zone');zone.addEventListener('dragover',e=>e.preventDefault());zone.addEventListener('drop',e=>{e.preventDefault();process(e.dataTransfer.files[0])});$('#recipe-optimize').addEventListener('click',()=>{const reviewed=$('#reviewed');if(reviewed)queries=reviewed.value.split(/\r?\n/).map(clean).filter(Boolean);const lines=[];for(const q of queries){const p=matches(q).filter(x=>x.available!==false).sort((a,b)=>a.price-b.price)[0];lines.push(p?`${p.name} en ${p.pharmacy}: ${money(p.price)}`:`Sin coincidencia disponible para “${esc(q)}”`)}$('#recipe-page-output').innerHTML=lines.length?`<b>Resultado para los medicamentos revisados</b><br>${lines.join('<br>')}<small class="recipe-result-note">Confirma presentación, dosis, receta, stock y precio final.</small>`:'<div class="recipe-warning">Escribe o confirma al menos un medicamento antes de optimizar.</div>'});$('#recipe-region').addEventListener('change',communes);$('#recipe-commune').addEventListener('change',load);$('.menu-btn').addEventListener('click',()=>$('.nav-links').classList.toggle('open'));communes();
